import platform
import os

ccflags = '-std=c++11 -Wall -Wextra -g -Og -DDEBUG'
ldflags = '--static'
cpppath = ['../include']
source  = ['main.cc', 'global.cc', 'init.cc', 'bitboard.cc', 'board.cc',
           'util.cc', 'move.cc']
target = 'vice++'

if platform.system() == 'Windows':
    env = Environment(tools   = ['mingw'],
                      CCFLAGS = ccflags,
                      CPPPATH = cpppath,
                      ENV     = os.environ)
else:
    env = Environment(CCFLAGS = ccflags,
                      CPPPATH = cpppath,
                      ENV     = os.environ)

env.Program(target    = target, 
            source    = source,
            LINKFLAGS = ldflags)
